jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: "actions/checkout@https://github.com/prasha94/buildm.git"
      - 
        name: "Set up JDK 11"
        uses: "actions/setup-java@https://github.com/prasha94/buildm.git"
        with: 
          distribution: adopt
          java-version: "11"
      - 
        name: "Build with Maven"
        run: "mvn --batch-mode --update-snapshots package"
name: "Java CI"
true: 
  - push
